# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := main_dst
### Generated for copy rule.
main: TOOLSET := $(TOOLSET)
main: out/Default/main FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += main
gl_gyp_main_dst_target_copies = main

### Rules for final target.
# Build our special outputs first.
$(obj).target/main_dst.stamp: | $(gl_gyp_main_dst_target_copies)

# Preserve order dependency of special output on deps.
$(gl_gyp_main_dst_target_copies): | $(builddir)/main

$(obj).target/main_dst.stamp: TOOLSET := $(TOOLSET)
$(obj).target/main_dst.stamp: $(builddir)/main FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/main_dst.stamp
# Add target alias
.PHONY: main_dst
main_dst: $(obj).target/main_dst.stamp

# Add target alias to "all" target.
.PHONY: all
all: main_dst

